### ISSUE TITLE
i run gpoddity.py and error "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 34: invalid continuation byte"

### ISSUE THREAD

**Issue by cmjlove1** [synacktiv/GPOddity#2]
i run gpoddity.py and error "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 34: invalid continuation byte"
![image](https://github.com/synacktiv/GPOddity/assets/88427245/1a525165-0aa2-46e4-adff-36185bf55c2d)

**Comment by q-roland** [comment]
Hi,
It seems like your `gpt.ini` file includes some non-UTF-8 characters. This is non-standard, but could happen if your AD installation was performed in a language with special characters ([ref](https://github.com/SSSD/sssd/issues/4138), [ref](https://lists.samba.org/archive/cifs-protocol/2019-March/003228.html)). I'm pushing a change in GPT.INI encoding handling that should solve the issue. Note that I don't have an AD setup at hand to perform in-depth tests on the fix. If you still encounter issues after the fix, please reopen the issue and I'Il set up a more extensive debugging environment.

**Comment by cmjlove1** [comment]
> Hi, It seems like your `gpt.ini` file includes some non-UTF-8 characters. This is non-standard, but could happen if your AD installation was performed in a language with special characters ([ref](https://github.com/SSSD/sssd/issues/4138), [ref](https://lists.samba.org/archive/cifs-protocol/2019-March/003228.html)). I'm pushing a change in GPT.INI encoding handling that should solve the issue. Note that I don't have an AD setup at hand to perform in-depth tests on the fix. If you still encounter issues after the fix, please reopen the issue and I'Il set up a more extensive debugging environment.


I solved it
![image](https://github.com/synacktiv/GPOddity/assets/88427245/5b60fe80-e20d-4964-8a7a-a25ef7b58090)
