### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by jsdhasfedssad** [synacktiv/GPOddity#3]
Hi,

Thank you for this tool. I have been waiting for a tool that can abuse GPOs in a safe way. However, during testing I encountered a couple of authentication issues.

Issue 1: First I added a user account named `gpoddity_user` and granted that full rights on the target GPO.  Then I attempted to use GPOddity authenticating with the username `gpoddity_user` and it's NTLM hash but that fails. See the error below. As you also can see I first verify the credentials. If I then use the exact same GPOddity command as before but authenticate using `gpoddity_user`'s plaintext password instead of its NTLM hash it works.
![gpo2](https://github.com/synacktiv/GPOddity/assets/97032878/b65bda55-ad6a-4c18-ae61-cf93c140bb04)

Issue 2: First I added a computer account named `gpoddity_computer` and granted that full rights on the target GPO.  Then I attempted to use GPOddity authenticating with the sAMAccountName `gpoddity_computer$` and it's plaintext password but that fails. See the error below. As you also can see I first verify the credentials. If I then use the exact same GPOddity command as before but authenticate using another added computer account's sAMAccountName `pentest1$` and it's plaintext password it works.
![gpo3 1](https://github.com/synacktiv/GPOddity/assets/97032878/7440dc3d-fc99-46d9-ab80-73576634db54)

![gpo3 3](https://github.com/synacktiv/GPOddity/assets/97032878/f24c6b19-a32d-4c06-9c15-7886ee7e0b0a)

**Comment by q-roland** [comment]
Hi!
Thank you for the detailed feedback.

Regarding issue 1, I was able to reproduce the problem. Authentication through NTLM hash was indeed not correctly handled during GPO retrieval. I am pushing a commit that will solve the issue (see [28b3f70](https://github.com/synacktiv/GPOddity/commit/28b3f70d272417fe62a97abda92474084cbd38c0)). Do not hesitate to test the fix and reopen the issue if any problem persists.

Regarding issue 2, you defined your machine account (`gpoddity_computer$`) with an underscore. This is **not** an allowed character in DNS host names within an Active Directory environment - see [here](https://learn.microsoft.com/en-us/troubleshoot/windows-server/identity/naming-conventions-for-computer-domain-site-ou): "DNS names can contain only alphabetic characters (A-Z), numeric characters (0-9), the minus sign (-), and the period (.)". Inserting an underscore in the host name for a machine will cause trouble when trying to access network services, which is very probably why you are seeing the error you highlighted (which does not appear with the name `pentest1$`).
